spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/corona
    username: sa
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    wiwy:
      covid: debug
    org.hibernate.SQL: debug
    #  org.hibernate.type: trace

